"""initial

Revision ID: 0cb7b988e2b9
Revises: 
Create Date: 2024-02-20 20:26:54.607413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0cb7b988e2b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table(
        "user",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default = sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_name",sa.String(length=50), nullable=False),
        sa.Column("password",sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default = sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name",sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("date",sa.Date(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("expense")
    # ### end Alembic commands ###
